spring:
  config:
    import: optional:file:.env

  datasource:
    url: jdbc:mysql://localhost:3306/guzip
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #테이블 자동 생성 및 업데이트


  jwt:
    secret: guzip_secret_key_slkdfjaiwefskdflskjdiwejfsldkjfwied